project:
  type: website
  render:
    - presentacion.qmd

website:
  title: "Investigacion_GRH"
  navbar:
    left:
      - href: presentacion.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

